---
- name: Install OpenSSH package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ sshd__packages }}"

- name: Create configuration file
  template:
    src: sshd_config.j2
    dest: "{{ sshd__config_file }}"
    owner: "{{ sshd__config_owner }}"
    group: "{{ sshd__config_group }}"
    mode: "{{ sshd__config_mode }}"
    validate: "{{ sshd__binary }} -t -f %s"
  notify: Reload SSH daemon

- name: Enabled and run SSH service
  service:
    name: "{{ sshd__service_name }}"
    enabled: true
    state: started
...
