---
- name: Display an IP address
  debug:
    msg:
      - "************************************************************"
      - "*                                                          *"
      - "*  The destination host IP address is {{ ansible_host }}   *"
      - "*                                                          *"
      - "************************************************************"
...
