---
#
# Immutable set of UNIX accounts.
#

#########
# STAFF #
#########
staff_accounts: {}


######################
# MANDATORY ACCOUNTS #
######################
# The 'special' account that is used to execute ansible commands.
mandatory_system_accounts:
    "ec2-user":
        name: ec2-user
        uid: 1000
        email: automation@co.nz
        display_name: Automation Account
        # password
        password: $6$GR7WE8wx$IJOXiwBZod/Recm9R8chd9QvybKAwDGncSu8opDuhhm9lEjHjkyZHASuS2M8cew1i6ZrwvI/7fQwopS5ezA2R.
        ssh_key:
            - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXe9KwzvToRjKN2Lotjy6OQeslNRm1i8wfsNRPjiLSPmXICQzjDVW6msGAyEX7g+50/cEk3bLBKb8DRJmArPuhV52yeTp1aub/SJM6JoF2VpzGr+AOVTDdAyX2rHqDOea/EPMDU3NQ4j5MGDAODTPJskiKMnCun9o7senj9DUSmgk7cQgdUZgTyTvft5AasVele7z5C1VnF1yfedsAWiejB2yUOdGfh/xU/Nqx+QIJ+fZtu8n7L5dUg9ZDd/8ud4nqgTDRApays6XX3mTdmG8KPhxqnKjFiR2PPOEc9ljNx25I6fj36XqIDuckd12iEaaWSvYUqOl/Pqo9o6RzIxFN automation"
        shell: /bin/bash

###################
# SYSTEM ACCOUNTS #
###################
system_accounts:
    backup:
        name: backup
        uid: 777
        non_interactive: true
        email: backup@qrious.co.nz
        display_name: Backup
        shell: /bin/bash

accounts: "{{ staff_accounts|combine(mandatory_system_accounts)|combine(system_accounts) }}"
...
