---
galaxy_info:
  author: Dmitrii Ageev
  license: GPLv2
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - 16
    - name: CentOS
      versions:
        - 7
  categories:
    - mail
    - aliases
...
