---
- include_tasks: preflight_checks.yml

- block:
    - include_tasks: install.yml
      when: logrotate__skip_installation is not defined
    - include_tasks: configuration.yml
    - include_tasks: run.yml
      when: logrotate__skip_installation is not defined
  when: logrotate__state == "present"

- block:
    - include_tasks: stop.yml
    - include_tasks: deconfiguration.yml
    - include_tasks: uninstall.yml
  when: logrotate__state == "absent"
...
