---
logrotate__files:
  - name: syslog
    path:
      - /var/log/syslog
      - /var/log/secure
      - /var/log/cron
      - /var/log/mail.info
      - /var/log/mail.warn
      - /var/log/mail.err
      - /var/log/mail.log
      - /var/log/daemon.log
      - /var/log/kern.log
      - /var/log/auth.log
      - /var/log/user.log
      - /var/log/lpr.log
      - /var/log/cron.log
      - /var/log/debug
      - /var/log/messages
    options:
      - rotate 9
      - weekly
      - missingok
      - notifempty
      - compress
      - delaycompress
      - sharedscripts
    scripts:
      # postrotate: /usr/bin/systemctl --quiet kill -s HUP rsyslog.service > /dev/null
      postrotate: /usr/bin/systemctl restart rsyslog > /dev/null
  - name: maillog
    path:
      - /var/log/maillog
    options:
      - rotate 9
      - weekly
      - missingok
      - notifempty
      - nocompress
      - sharedscripts
    scripts:
      postrotate: /usr/bin/systemctl restart rsyslog > /dev/null
  - name: yum
    path:
      - /var/log/yum.log
      - /var/log/alternatives.log
    options:
      - monthly
      - size 30k
      - compress
      - delaycompress
      - missingok
...
