---
- name: Add required repositories for Debian-based systems
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian" and item
  with_items: "{{ ntp__packages[ansible_distribution][ansible_distribution_major_version|int]['repositories'] }}"

- name: Add required repositories for RedHat-based systems
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat" and item
  with_items: "{{ ntp__packages[ansible_distribution][ansible_distribution_major_version|int]['repositories'] }}"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ ntp__packages[ansible_distribution][ansible_distribution_major_version|int]['packages'] }}"
  notify: Restart ntp service

- name: Create the application folder set
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ntp__user }}"
    group: "{{ ntp__group }}"
    mode: "{{ ntp__dir_mode }}"
  with_items: "{{ ntp__directories }}"
  when:
    - ntp__directories is defined
  notify: Restart ntp service
...
