---
- name: Delete service directories
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ ntp__directories }}"
  when:
    - ntp__directories is defined

- name: Deinstall required packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ ntp__packages[ansible_distribution][ansible_distribution_major_version|int]['packages'] }}"

# This task doesn't work and must be rewritten
- name: Delete previously installed repositories for RedHat-based systems
  yum:
    name: "{{ item }}"
    state: absent
  when: ansible_os_family == "RedHat" and item
  with_items: "{{ ntp__packages[ansible_distribution][ansible_distribution_major_version|int]['repositories'] }}"

- name: Delete previously installed repositories for Debian-based systems
  apt_repository:
    repo: "{{ item }}"
    state: absent
  when: ansible_os_family == "Debian" and item
  with_items: "{{ ntp__packages[ansible_distribution][ansible_distribution_major_version|int]['repositories'] }}"
...
