---
- block:
    - name: Delete the daemon user
      user:
        name: "{{ ntp__user }}"
        state: absent
        remove: yes

    - name: Delete the daemon group
      group:
        name: "{{ ntp__group }}"
        state: absent

  when: ntp__user != "root"
...
