---
- name: Configure Linux kernel parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    ignoreerrors: "no"
    reload: "yes"
  with_dict: "{{ sysctl__parameters.all }}"

- name: Configure parameters for Linux Kernel Version 3.0 and higher
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    ignoreerrors: "no"
    reload: "yes"
  with_dict: "{{ sysctl__parameters.kernel_v3 }}"
  when: sysctl__kernel_major_version|int >= 3
...
